name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
#       - name: Install dependencies
#       - run: |
#       conda env update --file environment.yml --name base
    - name: create environment.yml
      run: |
        conda install asv
        pip install scqubits
        conda env export > environment.yml --no-builds
#       conda update -n base -c defaults -c conda-forge conda
#       conda install -c anaconda numpy
#       conda install -c conda-forge scqubits
    - name: Test with asv
      run: |
        git checkout main && git checkout -
        pip install -e .
        asv machine --machine github-actions --yes
        asv continuous -f 1.25 main HEAD
    - name: Upload results to git
      run: |
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        git config --global user.name "$GIT_AUTHOR_NAME"
        asv gh-pages --no-push
        git push -f origin gh-pages:gh-pages
      env:
        GIT_AUTHOR_NAME: ${{ github.actor }}
        GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
#       asv continuous base pr --strict -e -v --config asv.conf.json
#       asv continuous base pr --strict -e -v --config asv.conf.json --environment 'existing'
#       asv run --config asv.conf.json -v --environment 'existing'
