name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
#       - name: Install dependencies
#       - run: |
#       conda env update --file environment.yml --name base
    - name: Test with asv
      run: |
        git fetch origin $GITHUB_BASE_REF:base $GITHUB_REF:pr
        conda install asv
        pip install -e .
        asv machine --yes
        asv continuous base pr --strict -e -v --config asv.conf.json
#       asv continuous base pr --strict -e -v --config asv.conf.json --environment 'existing'
#       asv run --config asv.conf.json -v --environment 'existing'
